### ISSUE TITLE
How long will the code be released?

### ISSUE THREAD

**Issue by xy1999729** [yimingdongml/Gauge-Equivariant-Transformer#1]
Thank you for your awesome work, I'm really interested in this word and hope your code can be released soon.

**Comment by QiangZiBro** [comment]
+1

**Comment by adonis-dym** [comment]
Thanks for your interest! We are currently focusing on another NeurIPS project and will release the code after NeurIPS this year. Best regards.

**Comment by yimingdongml** [comment]
Thanks for your interest! We are currently focusing on another NeurIPS project and will release the code after NeurIPS this year. Best regards
